feat: upgrading rtsf-at-checkout-device-scale service configuration a…
intel-iot-devkit/rtsf-at-checkout-reference-design pull request #15
Opened 2022-11-03 23:04 UTC by vli11

…nd profile

Signed-off-by: Valina Li <valina.li@intel.com>

2022-11-07 17:00 UTC, lenny-intel requested changes

2022-11-07 19:00 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +name: "device-scale-profile"
cas-usb-scale

2022-11-07 19:01 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +model: "device-scale-simulator"
something like CAS ED-15, @brian-intel can you confirm the model name?

2022-11-07 19:03 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +- "device-scale-label"
cas 
usb
ed-15 //if this proper model name we can replace it

2022-11-07 19:04 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +description: "A device for reading from serial scales"
Models a CAS USB scale device

2022-11-07 19:06 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +- name: "scale-item"
name: "weight"

2022-11-07 19:07 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/devices/device-list.toml
> +  Name = "device-scale"
cas-ed-15-001

2022-11-07 19:08 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/devices/device-list.toml
> +  Description = "device-scale-description"
CAS ED-15 USB scale

2022-11-07 19:08 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/devices/device-list.toml
> +  Labels = [ "device-scale-label" ]
same label as in the profile

2022-11-07 19:12 UTC, vli11 commented on rtsf-at-checkout-device-scale/cmd/res/configuration.toml
>    ScalePID = "6001"
make a separated PR for protocol properties, after the name change PR

2022-11-08 19:15 UTC, brian-intel approved these changes

2022-11-08 19:21 UTC, jim-wang-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +		//
remove this

2022-11-08 19:21 UTC, jim-wang-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +		//
remove this

2022-11-08 19:35 UTC, jim-wang-intel approved these changes

2022-11-08 20:33 UTC, lenny-intel requested changes

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +name: "cas-scale"
Also rename the file to `cas-scale.yaml` for consistency and get away from naming it with the service name.

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/cmd/res/profiles/device-scale.yaml
> +manufacturer: "Intel"
```suggestion
manufacturer: "CAS"
```

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +	// get device definition from sdk, then from device definition, get PID and VID from the protocol section
This comment can be removed.

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +	serialProtocol := protocols["serial"]
Should check that `serialProtocol ` isn't nil.

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +	serialPort, err := findSerialPort(serialProtocol["PID"], serialProtocol["VID"])
We should probably separate out getting PID and VID and check that they exist
```suggestion
        pid := serialProtocol["PID"]
        if len(pid) == 0 {
          handle error
        }
                vid := serialProtocol["VID"]
        if len(vid) == 0 {
          handle error
        }
	serialPort, err := findSerialPort(pid, vid)
```

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +	driver.lc.Debugf("[serialPort]: %v, err: %v", serialPort, err)
I don't like this since one or the other will not be set. I think it can be removed since both cases are handled below.

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +		drv.scaleConnected = true
```suggestion
                driver.lc.Debugf("[serialPort]: %v", serialPort)
		drv.scaleConnected = true
```

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +		scaleData, err := drv.scaleDevice.readWeight()
```suggestion
		scaleData, err := drv.scaleDevice.readWeight()
		if err != nil {
		   handle error
		}
```

2022-11-08 20:33 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/driver/scaleDriver.go
> +			driver.lc.Debugf("[scaleData]: %v, err: %v", v, err)
```suggestion
			driver.lc.Debugf("[scaleData]: %v", v)
```

2022-11-08 21:35 UTC, marcpfuller approved these changes

2022-11-08 21:37 UTC, merged