feat: remove zmq since edgex 2.3 not supporting it
intel-iot-devkit/rtsf-at-checkout-reference-design pull request #27
Opened 2022-11-29 21:52 UTC by vli11

Signed-off-by: Valina Li <valina.li@intel.com>

2022-11-29 22:41 UTC, brian-intel approved these changes

2022-11-29 22:44 UTC, jim-wang-intel approved these changes

2022-11-30 18:20 UTC, lenny-intel commented on rtsf-at-checkout-device-scale/Dockerfile
> +RUN go build -tags no_zmq -o device-scale cmd/main.go
Note: In Minnesota (current Edgex WIP) this build tag has been removed with the removal of ZMQ.  So for the Minnesota EdgeX services/sdks this is not needed.

2022-11-30 18:23 UTC, lenny-intel requested changes
One small change.

2022-11-30 18:23 UTC, lenny-intel commented on rtsf-at-checkout-loss-detector/Dockerfile
> +RUN apk update && apk add --no-cache make git linux-headers
I think `linux-headers` can also be removed since that is a CGO thing.

2022-11-30 18:42 UTC, lenny-intel approved these changes
LGTM

2022-11-30 18:51 UTC, marcpfuller approved these changes
LGTM

2022-11-30 18:52 UTC, merged