feat: rename devicename and profilename
intel-iot-devkit/rtsf-at-checkout-reference-design pull request #29
Opened 2022-11-30 22:10 UTC by vli11

Signed-off-by: Valina Li <valina.li@intel.com>

2022-11-30 22:12 UTC, vli11 commented
@lenny-intel  this is the first draft of rename devicename and profile name, I will make other files change if new names are good

2022-11-30 22:26 UTC, lenny-intel requested changes

2022-11-30 22:26 UTC, lenny-intel commented on loss-detection-app/res/device-rest/profiles/pos.yaml
> -name: "device-pos-rest"
Remove this file as it is handled by device-mqtt

2022-11-30 22:26 UTC, lenny-intel commented on loss-detection-app/res/device-rest/profiles/rfid-roi.yaml
> +name: "rfid-roi"
Remove this file as it is handled by device-mqtt

2022-11-30 22:26 UTC, lenny-intel commented on loss-detection-app/res/device-rest/profiles/scale.yaml
> +name: "scale"
Remove this file as it is handled by device-mqtt

2022-12-01 18:56 UTC, jim-wang-intel approved these changes
LGTM

2022-12-02 21:02 UTC, marcpfuller approved these changes
LGTM

2022-12-02 21:19 UTC, merged